---
- hosts: all
  become: true
  roles:
    - { role: geerlingguy.git }
    - { role: geerlingguy.mysql }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.php-xdebug }
    - { role: geerlingguy.composer }

  pre_tasks:
    - apt_repository: repo='ppa:ondrej/php' update_cache=yes

  vars:
    mysql_enabled_on_startup: yes
    mysql_packages:
      - mariadb-client
      - mariadb-server
      - python-mysqldb
    mysql_root_password: MysqlRootPassword
    mysql_databases:
      - name: database
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: user
        host: "%"
        password: PasswordForUser
        priv: "database.*:ALL"

    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "dev.local"
        root: "/var/www"
        index: "index.php"
        state: "present"
        extra_parameters: |
          location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass 127.0.0.1:9000;
          }

    php_enable_php_fpm: true
    php_packages_extra:
      - php7.0-soap
      - php7.0-mysql
      - php-xdebug
    php_version: 7.0
    php_webserver_daemon: "nginx"

    php_xdebug_remote_enable: yes
    php_xdebug_remote_connect_back: yes
    php_xdebug_remote_host: 192.168.50.1
    php_xdebug_remote_port: "9000"
    php_xdebug_cli_disable: no


  tasks:
  - name: Make sure we can get archived packages with Composer
    apt: name=unzip state=installed

  - name: Install Composer dependencies
    composer:
      command: install
      working_dir: "/var/www/"
    become_user: "www-data"
